version: '3'
services:
  db:
    #image: mariadb:10.5.8
    image: mysql:8.0.23

    # M1mac は、この行を除いて、下の一行をコメアウトしてください。
    # image: mysql@sha256:cd7a91b32bc0fa3140366becb7425985a2a259c004c8453b43378e7a1803c842

    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
    env_file: .env
    tty: true
    stdin_open: true
  
  rails:
    build:
      context: ./rails_app
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./rails_app/:/rails_app
      - rails-bundle:/user/local/bundle
      - ./_roothome/:/root
    depends_on:
      - db
    env_file: .env
    tty: true
    stdin_open: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST:${DB_HOST}
      - PMA_USER:root
      - PMA_PASSWORD:${MYSQL_ROOT_PASSWORD}
    ports:
      - 8888:80
    volumes:
      - pma-session:/sessions
    depends_on: 
      - rails
    env_file: .env

volumes:
  rails-bundle:
  db-data:
  pma-session: